In [1]:
import numpy as np

In [2]:
from games import PTTTGame 
from mcts import MCTS

In [3]:
game = PTTTGame(['|', '|'], [['|'], ['|']])

In [4]:
mcts = MCTS(game, 100000)

In [5]:
board = [0, 1, None, 0, None, 1, 0, None, 1]
game._terminal_rewards(board)

(True, [1, -1])

In [6]:
mcts.simulate(1)

In [7]:
mcts.solve()

In [8]:
mcts.get_strategy(0, 'pttt-infosets/player0-infoset.txt')

0 done out of 14482810
1000000 done out of 14482810
2000000 done out of 14482810
3000000 done out of 14482810
4000000 done out of 14482810
5000000 done out of 14482810
6000000 done out of 14482810
7000000 done out of 14482810
8000000 done out of 14482810
9000000 done out of 14482810
10000000 done out of 14482810
11000000 done out of 14482810
12000000 done out of 14482810
13000000 done out of 14482810
14000000 done out of 14482810


In [9]:
strategy = np.load('pttt_pl0.npy')

In [10]:
strategy[0]

array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.11111111, 0.11111111, 0.11111111], dtype=float32)

In [11]:
strategy[1:10]

array([[0.        , 0.06264841, 0.5420441 , 0.06587667, 0.06264856,
        0.0626484 , 0.07883702, 0.0626484 , 0.06264841],
       [0.06972373, 0.        , 0.06972373, 0.06972373, 0.5119339 ,
        0.06972373, 0.06972373, 0.06972373, 0.06972373],
       [0.125     , 0.125     , 0.        , 0.125     , 0.125     ,
        0.125     , 0.125     , 0.125     , 0.125     ],
       [0.05790646, 0.05790646, 0.05790646, 0.        , 0.59465486,
        0.05790646, 0.05790646, 0.05790646, 0.05790646],
       [0.08990334, 0.36321297, 0.09708661, 0.08991411, 0.        ,
        0.08990289, 0.0899029 , 0.09016943, 0.08990776],
       [0.10153155, 0.10153155, 0.10153155, 0.10153155, 0.28927916,
        0.        , 0.10153155, 0.10153155, 0.10153155],
       [0.37425202, 0.08246925, 0.08246925, 0.08246925, 0.08246925,
        0.08246925, 0.        , 0.08246925, 0.1309325 ],
       [0.05931379, 0.05931379, 0.05931379, 0.05931379, 0.5846891 ,
        0.05931379, 0.05931379, 0.        , 0.05942823],


In [12]:
strategy[10:26]

array([[0.        , 0.        , 0.07517252, 0.15842232, 0.16331404,
        0.21284766, 0.14070408, 0.10353656, 0.14600271],
       [0.        , 0.        , 0.69297546, 0.05218361, 0.08179072,
        0.0378578 , 0.04373271, 0.03708459, 0.05437509],
       [0.        , 0.08150315, 0.        , 0.09286957, 0.24386582,
        0.14205004, 0.13367246, 0.11172583, 0.19431312],
       [0.        , 0.73320866, 0.        , 0.04444854, 0.04445878,
        0.04444718, 0.0445226 , 0.04446077, 0.04445345],
       [0.        , 0.07030274, 0.16886227, 0.        , 0.25886902,
        0.12964776, 0.13882457, 0.09464319, 0.13885054],
       [0.        , 0.02382874, 0.02388422, 0.        , 0.02496518,
        0.02386074, 0.8495676 , 0.02841286, 0.02548068],
       [0.        , 0.16639324, 0.1489364 , 0.09009338, 0.        ,
        0.13379839, 0.20144749, 0.0995842 , 0.1597469 ],
       [0.        , 0.08258365, 0.05143835, 0.07649555, 0.        ,
        0.0630903 , 0.07749111, 0.0539951 , 0.5949059 ],


In [13]:
strategy[10030:111234]

array([[0.1944703 , 0.        , 0.20761979, ..., 0.1944703 , 0.22137372,
        0.        ],
       [0.1946709 , 0.        , 0.20681717, ..., 0.20765461, 0.19551472,
        0.        ],
       [0.20135634, 0.        , 0.19457465, ..., 0.20135634, 0.20135634,
        0.        ],
       ...,
       [0.25      , 0.        , 0.25      , ..., 0.25      , 0.        ,
        0.        ],
       [0.        , 0.        , 0.25      , ..., 0.25      , 0.        ,
        0.25      ],
       [0.        , 0.        , 0.24651733, ..., 0.26044807, 0.        ,
        0.24651733]], dtype=float32)

In [16]:
mcts.get_strategy(1, 'pttt-infosets/player1-infoset.txt')

0 done out of 8827459
1000000 done out of 8827459
2000000 done out of 8827459
3000000 done out of 8827459
4000000 done out of 8827459
5000000 done out of 8827459
6000000 done out of 8827459
7000000 done out of 8827459
8000000 done out of 8827459
